#!/usr/bin/env bash
# Parses Apache log files in a list format.
#   Groups visitors by IP and HTTP status code.
#   Displays the number of occurances, IP, and HTTP status code.

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
