#!/usr/bin/env bash
# SSH client configuration

Host *
	PasswordAuthenication no
	IdentifyFile ~/.ssh/school
	SendEnv LANG LC_*
	HashKnownHosts yes
	GSSAPIAuthenication yes
	GSSAPIDelegateCredentials no
